title: calvink19.co
description: My website!
show_downloads: false
# theme: jekyll-theme-console
Retry-After: 1sec

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: false # false (default) or true

footer: '2026 © calvink19'
